project_id = "hncirnpdfwglagjniapy"

[functions.link-account]
verify_jwt = false

[functions.admin-link-account]
verify_jwt = false

[functions.manage-user-role]
verify_jwt = false

[functions.verify-session-pin]
verify_jwt = false

[functions.create-login-confirmation]
verify_jwt = false

[functions.verify-login-confirmation]
verify_jwt = false

[functions.manage-nav-permissions]
verify_jwt = false

[functions.send-telegram-summary]
verify_jwt = false

[functions.notify-pdf-export]
verify_jwt = false

[functions.webauthn-register]
verify_jwt = false

[functions.webauthn-authenticate]
verify_jwt = false

[functions.manage-webauthn]
verify_jwt = false

[functions.send-settlement]
verify_jwt = false

[functions.sync-staff-from-zt]
verify_jwt = false