project_id = "hncirnpdfwglagjniapy"

[functions.link-account]
verify_jwt = false

[functions.admin-link-account]
verify_jwt = false

[functions.manage-user-role]
verify_jwt = false

[functions.verify-session-pin]
verify_jwt = false