ALTER TYPE staff_role ADD VALUE IF NOT EXISTS 'gl';
ALTER TYPE staff_role ADD VALUE IF NOT EXISTS 'waiter_gl';
ALTER TYPE staff_role ADD VALUE IF NOT EXISTS 'kitchen_gl';
ALTER TYPE staff_role ADD VALUE IF NOT EXISTS 'all';